# Generated by Django 4.0.6 on 2022-08-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClasslistCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='.')),
                ('valid', models.BooleanField(default=False)),
                ('warnings_errors_list', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.TextField(null=True, unique=True)),
                ('student_name', models.TextField()),
                ('paper_number', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
