# SPDX-License-Identifier: FSFAP
# Copyright (C) 2023 Edith Coates

# Pull base image
FROM python:3.10.2-slim-bullseye

# Set environment variables
ENV PIP_DISABLE_PIP_VERSION_CHECK 1
ENV PYTHONUNBUFFERED 1
ENV PLOM_USING_DOCKER 1

# Set work directory
WORKDIR /code

RUN apt update -y && apt install -y cmake gcc latexmk texlive-pictures build-essential git

# Install dependencies
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# Copy project
COPY . .
