# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2024-2025 Colin B. Macdonald
# Copyright (C) 2024 Andrew Rechnitzer
# Copyright (C) 2025 Aidan Murphy

[[rubric]]
kind = "absolute"
value = 1
out_of = 3
text = "Newton's law of cooling mentioned but no diff eqn or general solution"
username = "manager"
question_index = 4
versions = "1"

[[rubric]]
kind = "absolute"
value = 1
out_of = 3
text = "Incorrect differential equation stated"
username = "manager"
question_index = 4


[[rubric]]
kind = "absolute"
value = 2
out_of = 3
text = "Differential equation formed but error in solution"
username = "manager"
question_index = 4

[[rubric]]
kind = "absolute"
value = 3
out_of = 3
text = "Differential equation formed and general solution stated"
username = "manager"
question_index = 4

[[rubric]]
kind = "absolute"
value = 3
out_of = 3
text = "Differential equation formed and solved to find general solution"
username = "manager"
question_index = 4

[[rubric]]
kind = "relative"
value = -1
out_of = 0
text = "Answer should include units\n(such as \"{param1}\")"
meta = "Note this rubric differs between versions of the question."
username = "manager"
question_index = 4
versions = ""
parameters = [["{param1}", ["s", "year", "ms"]]]


[[rubric]]
kind = "relative"
value = 1
out_of = 0
text = "some initial progress"
meta = "The student has made some minimal progress."
username = "manager"
question_index = 4

[[rubric]]
kind = "relative"
value = 2
out_of = 0
text = "Correct set-up"
meta = "The student has set up the problem correctly."
username = "manager"
question_index = 4

[[rubric]]
kind = "relative"
value = 1
out_of = 0
text = "small algebra error"
meta = "The student has made minor algebra error"
username = "manager"
question_index = 4

[[rubric]]
kind = "relative"
value = 1
out_of = 0
text = "small arithmetic error"
meta = "The student has made minor arithmetic error"
username = "manager"
question_index = 4

[[rubric]]
kind = "neutral"
text = "be careful"
tags = "demo"
meta = "Student made an inconsequential error."
question_index = 4
username = "manager"

[[rubric]]
kind = "neutral"
text = "hard to read"
tags = "demo"
meta = "Student handwriting is making marking hard"
question_index = 4
username = "manager"

[[rubric]]
kind = "neutral"
text = "layout work more carefully"
tags = "demo"
meta = "Student needs to learn how to set out their work so someone else can follow."
question_index = 4
username = "manager"
