# Generated by Django 5.2.1 on 2025-12-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Mark", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="markingtask",
            name="marking_priority",
            field=models.FloatField(default=0.0),
        ),
    ]
