# Generated by Django 5.1.7 on 2025-07-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Mark", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="markingtasktag",
            name="task",
            field=models.ManyToManyField(related_name="tag", to="Mark.markingtask"),
        ),
    ]
