# Generated by Django 5.1.7 on 2025-07-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Mark", "0003_alter_markingtasktag_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="markingtasktag",
            name="task",
            field=models.ManyToManyField(to="Mark.markingtask"),
        ),
    ]
