# Generated by Django 4.0.6 on 2022-08-15 18:39

import TestCreator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReferencePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename_slug', models.TextField(default='')),
                ('pdf', models.FileField(upload_to=TestCreator.models.temp_filename_path)),
                ('num_pages', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TestSpecInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.TextField()),
                ('short_name', models.TextField()),
                ('n_versions', models.PositiveIntegerField(default=0)),
                ('n_to_produce', models.PositiveIntegerField(default=0)),
                ('n_questions', models.IntegerField(default=0)),
                ('total_marks', models.IntegerField(default=0)),
                ('pages', models.JSONField(default=dict)),
                ('dnm_page_submitted', models.BooleanField(default=False)),
                ('validate_page_sumbitted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TestSpecQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(default=1)),
                ('label', models.TextField()),
                ('mark', models.PositiveIntegerField(default=0)),
                ('shuffle', models.BooleanField(default=None, null=True)),
            ],
        ),
    ]
