# Generated by Django 4.0.5 on 2022-06-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReferencePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename_slug', models.CharField(default='', max_length=100)),
                ('pdf', models.FileField(upload_to='')),
            ],
        ),
    ]
