# Generated by Django 4.0.5 on 2022-06-27 21:51

from django.db import migrations, models
import TestCreator.models


class Migration(migrations.Migration):

    dependencies = [
        ('TestCreator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencepdf',
            name='pdf',
            field=models.FileField(upload_to=TestCreator.models.temp_filename_path),
        ),
    ]
