# Generated by Django 4.0.6 on 2022-08-15 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestCreator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testspecinfo',
            old_name='validate_page_sumbitted',
            new_name='validate_page_submitted',
        ),
    ]
