# Generated by Django 4.0.5 on 2022-06-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestCreator', '0002_alter_referencepdf_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencepdf',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
    ]
