# Generated by Django 4.0.5 on 2022-06-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestCreator', '0003_referencepdf_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencepdf',
            name='num_pages',
            field=models.IntegerField(default=0),
        ),
    ]
