# Generated by Django 4.0.5 on 2022-06-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestCreator', '0004_referencepdf_num_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSpecInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=150)),
                ('short_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='referencepdf',
            name='uuid',
        ),
    ]
