# Generated by Django 4.0.5 on 2022-06-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestCreator', '0005_testspecinfo_remove_referencepdf_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='testspecinfo',
            name='n_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testspecinfo',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
    ]
