# Generated by Django 4.0.5 on 2022-07-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestCreator', '0006_testspecinfo_n_questions_testspecinfo_total_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSpecQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(default=1)),
                ('label', models.CharField(max_length=15)),
                ('mark', models.PositiveIntegerField(default=0)),
                ('shuffle', models.CharField(choices=[('S', 'Shuffle'), ('F', 'Fix')], max_length=100)),
            ],
        ),
    ]
