# Generated by Django 4.0.6 on 2022-07-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestCreator', '0009_alter_testspecinfo_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='testspecinfo',
            name='n_versions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testspecinfo',
            name='long_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testspecinfo',
            name='short_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testspecquestion',
            name='label',
            field=models.TextField(),
        ),
    ]
