# Generated by Django 4.0.6 on 2022-07-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestCreator', '0009_alter_testspecinfo_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testspecinfo',
            name='long_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testspecinfo',
            name='short_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testspecquestion',
            name='label',
            field=models.TextField(),
        ),
    ]
