# Generated by Django 4.0.6 on 2022-07-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestCreator', '0010_alter_testspecinfo_long_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testspecinfo',
            name='n_versions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
