# Generated by Django 4.0.6 on 2022-07-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestCreator', '0011_testspecinfo_n_versions'),
    ]

    operations = [
        migrations.AddField(
            model_name='testspecinfo',
            name='n_to_produce',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
