# Generated by Django 4.0.6 on 2022-07-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestCreator', '0012_testspecinfo_n_to_produce'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSpecProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_names_completed', models.BooleanField(default=False)),
                ('is_versions_pdf_completed', models.BooleanField(default=False)),
                ('is_id_page_completed', models.BooleanField(default=False)),
                ('is_question_page_completed', models.BooleanField(default=False)),
                ('are_questions_completed', models.JSONField(default=dict)),
                ('are_pages_selected', models.JSONField(default=dict)),
            ],
        ),
        migrations.AlterField(
            model_name='referencepdf',
            name='filename_slug',
            field=models.TextField(default=''),
        ),
    ]
