# Generated by Django 4.0.6 on 2022-07-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestCreator', '0013_testspecprogress_alter_referencepdf_filename_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='testspecprogress',
            name='is_dnm_page_completed',
            field=models.BooleanField(default=False),
        ),
    ]
