# Generated by Django 4.0.6 on 2022-07-19 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestCreator', '0014_testspecprogress_is_dnm_page_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testspecprogress',
            name='are_pages_selected',
        ),
    ]
