# Generated by Django 4.0.6 on 2022-07-20 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestCreator', '0010_testspecinfo_n_versions_alter_testspecinfo_long_name_and_more'),
        ('TestCreator', '0015_remove_testspecprogress_are_pages_selected'),
    ]

    operations = [
    ]
