# Generated by Django 4.0.6 on 2022-08-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestCreator', '0016_merge_20220720_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='testspecprogress',
            name='is_validate_page_completed',
            field=models.BooleanField(default=False),
        ),
    ]
