# Generated by Django 4.1 on 2022-08-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestCreator', '0017_testspecprogress_is_validate_page_completed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestSpecProgress',
        ),
        migrations.AddField(
            model_name='testspecinfo',
            name='dnm_page_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testspecinfo',
            name='validate_page_sumbitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testspecquestion',
            name='shuffle',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
