# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2022-2023 Colin B. Macdonald

name = "plomdemo"
longName = "Midterm Demo using Plom"

numberOfVersions = 2
numberOfPages = 6
totalMarks = 20
numberOfQuestions = 3
idPage = 1
doNotMarkPages = [2]

[[question]]
pages = [3]
mark = 5

[[question]]
label = "Q(2)"
pages = [4]
mark = 5
select = 1

[[question]]
label = "Ex.3"
pages = [5, 6]
mark = 10
