# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2022 Edith Coates
# Copyright (C) 2022-2023 Brennen Chiu

from django.urls import path

from .views import (
    ScannerHomeView,
    BundleSplittingProgressView,
    BundleSplittingUpdateView,
    ManageBundleView,
    BundleThumbnailView,
    UpdateQRProgressView,
    GetBundleView,
    GetBundleNavFragmentView,
    GetBundleImageView,
    GetBundleThumbnailView,
    GetStagedBundleFragmentView,
    RemoveBundleView,
    ReadQRcodesView,
    QRParsingProgressAlert,
    BundleTableView,
    PushPageImage,
    PushAllPageImages,
    PagePushingUpdateView,
    FlagPageImage,
    ScannerSummaryView,
    ScannerPushedImageView,
    ScannerPushedImageWrapView,
    DiscardImageView,
    ExtraliseImageView,
    KnowifyImageView,
    UnknowifyImageView,
    RotateImageClockwise,
    RotateImageCounterClockwise,
    GetRotatedThumbnailView,
    GetRotatedBundleImageView,
)


urlpatterns = [
    path("", ScannerHomeView.as_view(), name="scan_home"),
    path(
        "<timestamp>/<int:index>/",
        ManageBundleView.as_view(),
        name="scan_manage_bundle",
    ),
    path(
        "nav/<timestamp>/<int:index>/",
        GetBundleNavFragmentView.as_view(),
        name="scan_nav_bundle",
    ),
    path(
        "thumbnails/<timestamp>/<int:index>",
        GetBundleThumbnailView.as_view(),
        name="scan_get_thumbnail",
    ),
    path(
        "thumbnail_rot/<timestamp>/<int:index>",
        GetRotatedThumbnailView.as_view(),
        name="scan_get_rotated_thumbnail",
    ),
    path(
        "thumbnails/<timestamp>",
        BundleThumbnailView.as_view(),
        name="scan_bundle_thumbnails",
    ),
    path(
        "split/<timestamp>/",
        BundleSplittingProgressView.as_view(),
        name="scan_image_progress",
    ),
    path(
        "split/<timestamp>/update/",
        BundleSplittingUpdateView.as_view(),
        name="scan_image_update",
    ),
    path(
        "bundle/<timestamp>/",
        GetBundleView.as_view(),
        name="scan_get_bundle",
    ),
    path(
        "bundle_staged/<timestamp>/",
        GetStagedBundleFragmentView.as_view(),
        name="scan_get_staged_bundle_fragment",
    ),
    path(
        "bundle/<timestamp>/<int:index>/",
        GetBundleImageView.as_view(),
        name="scan_get_image",
    ),
    path(
        "bundle_rot/<timestamp>/<int:index>/",
        GetRotatedBundleImageView.as_view(),
        name="scan_get_rotated_image",
    ),
    path(
        "delete/<timestamp>/",
        RemoveBundleView.as_view(),
        name="scan_remove_bundle",
    ),
    path(
        "read/<timestamp>",
        ReadQRcodesView.as_view(),
        name="scan_read_qr",
    ),
    path(
        "read/<timestamp>/<int:index>/",
        UpdateQRProgressView.as_view(),
        name="scan_qr_progress",
    ),
    path(
        "read/<timestamp>/alert/",
        QRParsingProgressAlert.as_view(),
        name="scan_qr_alert",
    ),
    path(
        "read/table/<timestamp>/<int:index>/",
        BundleTableView.as_view(),
        name="scan_bundle_table",
    ),
    path(
        "push/<timestamp>/<int:index>/",
        PushPageImage.as_view(),
        name="scan_push_img",
    ),
    path("push/<timestamp>/all/", PushAllPageImages.as_view(), name="scan_push_all"),
    path(
        "push_update/<timestamp>/<int:index>/",
        PagePushingUpdateView.as_view(),
        name="scan_push_update",
    ),
    path(
        "flag/<timestamp>/<int:index>/",
        FlagPageImage.as_view(),
        name="scan_flag_img",
    ),
    path(
        "summary/",
        ScannerSummaryView.as_view(),
        name="scan_summary",
    ),
    path(
        "summary/pushed_img/<int:img_pk>",
        ScannerPushedImageView.as_view(),
        name="scan_pushed_img",
    ),
    path(
        "summary/pushed_img_wrap/<int:img_pk>",
        ScannerPushedImageWrapView.as_view(),
        name="scan_pushed_img_wrap",
    ),
    path(
        "discard/<timestamp>/<int:index>/",
        DiscardImageView.as_view(),
        name="discard_image",
    ),
    path(
        "unknowify/<timestamp>/<int:index>/",
        UnknowifyImageView.as_view(),
        name="unknowify_image",
    ),
    path(
        "knowify/<timestamp>/<int:index>/",
        KnowifyImageView.as_view(),
        name="knowify_image",
    ),
    path(
        "extralise/<timestamp>/<int:index>/",
        ExtraliseImageView.as_view(),
        name="extralise_image",
    ),
    path(
        "rotate/clockwise/<timestamp>/<int:index>/",
        RotateImageClockwise.as_view(),
        name="rotate_img_cw",
    ),
    path(
        "rotate/counterclockwise/<timestamp>/<int:index>/",
        RotateImageCounterClockwise.as_view(),
        name="rotate_img_ccw",
    ),
]
