# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_annotator.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_annotator(object):
    def setupUi(self, annotator):
        annotator.setObjectName("annotator")
        annotator.resize(862, 670)
        self.gridLayout_5 = QtWidgets.QGridLayout(annotator)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_2 = QtWidgets.QFrame(annotator)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.cancelButton = QtWidgets.QPushButton(self.frame_2)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout_2.addWidget(self.cancelButton, 0, 2, 1, 1)
        self.finishedButton = QtWidgets.QPushButton(self.frame_2)
        self.finishedButton.setObjectName("finishedButton")
        self.gridLayout_2.addWidget(self.finishedButton, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_2, 3, 1, 1, 1)
        self.pageFrame = QtWidgets.QFrame(annotator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageFrame.sizePolicy().hasHeightForWidth())
        self.pageFrame.setSizePolicy(sizePolicy)
        self.pageFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pageFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pageFrame.setObjectName("pageFrame")
        self.pageFrameGrid = QtWidgets.QGridLayout(self.pageFrame)
        self.pageFrameGrid.setContentsMargins(3, 3, 3, 3)
        self.pageFrameGrid.setObjectName("pageFrameGrid")
        self.gridLayout_5.addWidget(self.pageFrame, 0, 0, 4, 1)
        self.markBox = QtWidgets.QGroupBox(annotator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.markBox.sizePolicy().hasHeightForWidth())
        self.markBox.setSizePolicy(sizePolicy)
        self.markBox.setObjectName("markBox")
        self.markGrid = QtWidgets.QGridLayout(self.markBox)
        self.markGrid.setContentsMargins(3, 3, 3, 3)
        self.markGrid.setSpacing(3)
        self.markGrid.setObjectName("markGrid")
        self.gridLayout_5.addWidget(self.markBox, 1, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(annotator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.commentGrid = QtWidgets.QGridLayout(self.groupBox_3)
        self.commentGrid.setContentsMargins(3, 3, 3, 3)
        self.commentGrid.setSpacing(3)
        self.commentGrid.setObjectName("commentGrid")
        self.gridLayout_5.addWidget(self.groupBox_3, 2, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(annotator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_3.setSpacing(3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.boxButton = QtWidgets.QToolButton(self.groupBox)
        self.boxButton.setObjectName("boxButton")
        self.gridLayout_3.addWidget(self.boxButton, 3, 2, 1, 1)
        self.crossButton = QtWidgets.QToolButton(self.groupBox)
        self.crossButton.setObjectName("crossButton")
        self.gridLayout_3.addWidget(self.crossButton, 3, 1, 1, 1)
        self.tickButton = QtWidgets.QToolButton(self.groupBox)
        self.tickButton.setToolTipDuration(-1)
        self.tickButton.setObjectName("tickButton")
        self.gridLayout_3.addWidget(self.tickButton, 3, 0, 1, 1)
        self.textButton = QtWidgets.QToolButton(self.groupBox)
        self.textButton.setObjectName("textButton")
        self.gridLayout_3.addWidget(self.textButton, 3, 3, 1, 1)
        self.redoButton = QtWidgets.QToolButton(self.groupBox)
        self.redoButton.setObjectName("redoButton")
        self.gridLayout_3.addWidget(self.redoButton, 2, 0, 1, 1)
        self.penButton = QtWidgets.QToolButton(self.groupBox)
        self.penButton.setObjectName("penButton")
        self.gridLayout_3.addWidget(self.penButton, 2, 1, 1, 1)
        self.zoomButton = QtWidgets.QToolButton(self.groupBox)
        self.zoomButton.setObjectName("zoomButton")
        self.gridLayout_3.addWidget(self.zoomButton, 2, 2, 1, 1)
        self.panButton = QtWidgets.QToolButton(self.groupBox)
        self.panButton.setObjectName("panButton")
        self.gridLayout_3.addWidget(self.panButton, 2, 3, 1, 1)
        self.moveButton = QtWidgets.QToolButton(self.groupBox)
        self.moveButton.setObjectName("moveButton")
        self.gridLayout_3.addWidget(self.moveButton, 4, 3, 1, 1)
        self.deleteButton = QtWidgets.QToolButton(self.groupBox)
        self.deleteButton.setObjectName("deleteButton")
        self.gridLayout_3.addWidget(self.deleteButton, 4, 2, 1, 1)
        self.lineButton = QtWidgets.QToolButton(self.groupBox)
        self.lineButton.setObjectName("lineButton")
        self.gridLayout_3.addWidget(self.lineButton, 4, 1, 1, 1)
        self.undoButton = QtWidgets.QToolButton(self.groupBox)
        self.undoButton.setObjectName("undoButton")
        self.gridLayout_3.addWidget(self.undoButton, 4, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 0, 1, 1, 1)

        self.retranslateUi(annotator)
        QtCore.QMetaObject.connectSlotsByName(annotator)
        annotator.setTabOrder(self.tickButton, self.crossButton)
        annotator.setTabOrder(self.crossButton, self.boxButton)
        annotator.setTabOrder(self.boxButton, self.textButton)
        annotator.setTabOrder(self.textButton, self.undoButton)
        annotator.setTabOrder(self.undoButton, self.lineButton)
        annotator.setTabOrder(self.lineButton, self.deleteButton)
        annotator.setTabOrder(self.deleteButton, self.moveButton)
        annotator.setTabOrder(self.moveButton, self.redoButton)
        annotator.setTabOrder(self.redoButton, self.penButton)
        annotator.setTabOrder(self.penButton, self.zoomButton)
        annotator.setTabOrder(self.zoomButton, self.panButton)
        annotator.setTabOrder(self.panButton, self.finishedButton)
        annotator.setTabOrder(self.finishedButton, self.cancelButton)

    def retranslateUi(self, annotator):
        _translate = QtCore.QCoreApplication.translate
        annotator.setWindowTitle(_translate("annotator", "Annotate paper"))
        self.cancelButton.setText(_translate("annotator", "Cancel"))
        self.finishedButton.setText(_translate("annotator", "Finished"))
        self.markBox.setTitle(_translate("annotator", "Enter Mark"))
        self.groupBox_3.setTitle(_translate("annotator", "Comment list"))
        self.groupBox.setTitle(_translate("annotator", "Tools"))
        self.boxButton.setToolTip(_translate("annotator", "press d or l"))
        self.boxButton.setText(_translate("annotator", "..."))
        self.crossButton.setToolTip(_translate("annotator", "press s or k"))
        self.crossButton.setText(_translate("annotator", "..."))
        self.tickButton.setToolTip(_translate("annotator", "press a or j"))
        self.tickButton.setText(_translate("annotator", "..."))
        self.textButton.setToolTip(_translate("annotator", "press f or semi-colon"))
        self.textButton.setText(_translate("annotator", "..."))
        self.redoButton.setToolTip(_translate("annotator", "press q or u"))
        self.redoButton.setText(_translate("annotator", "..."))
        self.penButton.setToolTip(_translate("annotator", "press w or i"))
        self.penButton.setText(_translate("annotator", "..."))
        self.zoomButton.setToolTip(_translate("annotator", "press e or o"))
        self.zoomButton.setText(_translate("annotator", "..."))
        self.panButton.setToolTip(_translate("annotator", "press r or p"))
        self.panButton.setText(_translate("annotator", "..."))
        self.moveButton.setToolTip(_translate("annotator", "press v or /"))
        self.moveButton.setText(_translate("annotator", "..."))
        self.deleteButton.setToolTip(_translate("annotator", "press c or period"))
        self.deleteButton.setText(_translate("annotator", "..."))
        self.lineButton.setToolTip(_translate("annotator", "press x or comma"))
        self.lineButton.setText(_translate("annotator", "..."))
        self.undoButton.setToolTip(_translate("annotator", "press z or m"))
        self.undoButton.setText(_translate("annotator", "..."))

