# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../qtCreatorFiles/ui_annotator_righthandmouse.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_annotator_rhm(object):
    def setupUi(self, annotator_rhm):
        annotator_rhm.setObjectName("annotator_rhm")
        annotator_rhm.setWindowModality(QtCore.Qt.WindowModal)
        annotator_rhm.resize(862, 670)
        self.gridLayout = QtWidgets.QGridLayout(annotator_rhm)
        self.gridLayout.setObjectName("gridLayout")
        self.hideableBox = QtWidgets.QFrame(annotator_rhm)
        self.hideableBox.setObjectName("hideableBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.hideableBox)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.hideableBox)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.modeLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.modeLayout.setObjectName("modeLayout")
        self.hideButton = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hideButton.sizePolicy().hasHeightForWidth())
        self.hideButton.setSizePolicy(sizePolicy)
        self.hideButton.setObjectName("hideButton")
        self.modeLayout.addWidget(self.hideButton)
        self.modeLabel = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modeLabel.sizePolicy().hasHeightForWidth())
        self.modeLabel.setSizePolicy(sizePolicy)
        self.modeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.modeLabel.setObjectName("modeLabel")
        self.modeLayout.addWidget(self.modeLabel)
        self.markLabel = QtWidgets.QLabel(self.frame_3)
        self.markLabel.setObjectName("markLabel")
        self.modeLayout.addWidget(self.markLabel)
        self.verticalLayout.addWidget(self.frame_3)
        self.groupBox = QtWidgets.QGroupBox(self.hideableBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.toolLayout = QtWidgets.QGridLayout(self.groupBox)
        self.toolLayout.setObjectName("toolLayout")
        self.crossButton = QtWidgets.QToolButton(self.groupBox)
        self.crossButton.setMinimumSize(QtCore.QSize(45, 0))
        self.crossButton.setObjectName("crossButton")
        self.toolLayout.addWidget(self.crossButton, 0, 4, 1, 1)
        self.commentUpButton = QtWidgets.QToolButton(self.groupBox)
        self.commentUpButton.setMinimumSize(QtCore.QSize(45, 0))
        self.commentUpButton.setToolTipDuration(-1)
        self.commentUpButton.setObjectName("commentUpButton")
        self.toolLayout.addWidget(self.commentUpButton, 0, 5, 1, 1)
        self.tickButton = QtWidgets.QToolButton(self.groupBox)
        self.tickButton.setMinimumSize(QtCore.QSize(45, 0))
        self.tickButton.setToolTipDuration(-1)
        self.tickButton.setObjectName("tickButton")
        self.toolLayout.addWidget(self.tickButton, 2, 4, 1, 1)
        self.commentButton = QtWidgets.QToolButton(self.groupBox)
        self.commentButton.setMinimumSize(QtCore.QSize(45, 0))
        self.commentButton.setToolTipDuration(-1)
        self.commentButton.setObjectName("commentButton")
        self.toolLayout.addWidget(self.commentButton, 2, 5, 1, 1)
        self.boxButton = QtWidgets.QToolButton(self.groupBox)
        self.boxButton.setMinimumSize(QtCore.QSize(45, 0))
        self.boxButton.setObjectName("boxButton")
        self.toolLayout.addWidget(self.boxButton, 3, 4, 1, 1)
        self.commentDownButton = QtWidgets.QToolButton(self.groupBox)
        self.commentDownButton.setMinimumSize(QtCore.QSize(45, 0))
        self.commentDownButton.setToolTipDuration(-1)
        self.commentDownButton.setObjectName("commentDownButton")
        self.toolLayout.addWidget(self.commentDownButton, 3, 5, 1, 1)
        self.penButton = QtWidgets.QToolButton(self.groupBox)
        self.penButton.setMinimumSize(QtCore.QSize(45, 0))
        self.penButton.setObjectName("penButton")
        self.toolLayout.addWidget(self.penButton, 0, 6, 1, 1)
        self.textButton = QtWidgets.QToolButton(self.groupBox)
        self.textButton.setMinimumSize(QtCore.QSize(45, 0))
        self.textButton.setObjectName("textButton")
        self.toolLayout.addWidget(self.textButton, 2, 6, 1, 1)
        self.lineButton = QtWidgets.QToolButton(self.groupBox)
        self.lineButton.setMinimumSize(QtCore.QSize(45, 0))
        self.lineButton.setObjectName("lineButton")
        self.toolLayout.addWidget(self.lineButton, 3, 6, 1, 1)
        self.deleteButton = QtWidgets.QToolButton(self.groupBox)
        self.deleteButton.setMinimumSize(QtCore.QSize(45, 0))
        self.deleteButton.setObjectName("deleteButton")
        self.toolLayout.addWidget(self.deleteButton, 3, 3, 1, 1)
        self.undoButton = QtWidgets.QToolButton(self.groupBox)
        self.undoButton.setMinimumSize(QtCore.QSize(45, 0))
        self.undoButton.setObjectName("undoButton")
        self.toolLayout.addWidget(self.undoButton, 2, 3, 1, 1)
        self.redoButton = QtWidgets.QToolButton(self.groupBox)
        self.redoButton.setMinimumSize(QtCore.QSize(45, 0))
        self.redoButton.setObjectName("redoButton")
        self.toolLayout.addWidget(self.redoButton, 0, 3, 1, 1)
        self.panButton = QtWidgets.QToolButton(self.groupBox)
        self.panButton.setMinimumSize(QtCore.QSize(45, 0))
        self.panButton.setObjectName("panButton")
        self.toolLayout.addWidget(self.panButton, 0, 2, 1, 1)
        self.zoomButton = QtWidgets.QToolButton(self.groupBox)
        self.zoomButton.setMinimumSize(QtCore.QSize(45, 0))
        self.zoomButton.setObjectName("zoomButton")
        self.toolLayout.addWidget(self.zoomButton, 2, 2, 1, 1)
        self.moveButton = QtWidgets.QToolButton(self.groupBox)
        self.moveButton.setMinimumSize(QtCore.QSize(45, 0))
        self.moveButton.setObjectName("moveButton")
        self.toolLayout.addWidget(self.moveButton, 3, 2, 1, 1)
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 1, 1, 1)
        self.keyHelpButton = QtWidgets.QPushButton(self.frame)
        self.keyHelpButton.setObjectName("keyHelpButton")
        self.gridLayout_4.addWidget(self.keyHelpButton, 0, 0, 1, 1)
        self.zoomCB = QtWidgets.QComboBox(self.frame)
        self.zoomCB.setObjectName("zoomCB")
        self.gridLayout_4.addWidget(self.zoomCB, 0, 2, 1, 1)
        self.toolLayout.addWidget(self.frame, 5, 2, 1, 5)
        self.verticalLayout.addWidget(self.groupBox)
        self.markBox = QtWidgets.QGroupBox(self.hideableBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.markBox.sizePolicy().hasHeightForWidth())
        self.markBox.setSizePolicy(sizePolicy)
        self.markBox.setTitle("")
        self.markBox.setObjectName("markBox")
        self.markGrid = QtWidgets.QGridLayout(self.markBox)
        self.markGrid.setContentsMargins(3, 3, 3, 3)
        self.markGrid.setSpacing(3)
        self.markGrid.setObjectName("markGrid")
        self.verticalLayout.addWidget(self.markBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.hideableBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.commentGrid = QtWidgets.QGridLayout(self.groupBox_3)
        self.commentGrid.setContentsMargins(3, 3, 3, 3)
        self.commentGrid.setSpacing(3)
        self.commentGrid.setObjectName("commentGrid")
        self.verticalLayout.addWidget(self.groupBox_3)
        self.frame_2 = QtWidgets.QFrame(self.hideableBox)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.ebLayout = QtWidgets.QGridLayout(self.frame_2)
        self.ebLayout.setObjectName("ebLayout")
        self.finishNoRelaunchButton = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.finishNoRelaunchButton.sizePolicy().hasHeightForWidth())
        self.finishNoRelaunchButton.setSizePolicy(sizePolicy)
        self.finishNoRelaunchButton.setObjectName("finishNoRelaunchButton")
        self.ebLayout.addWidget(self.finishNoRelaunchButton, 0, 2, 1, 1)
        self.cancelButton = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelButton.sizePolicy().hasHeightForWidth())
        self.cancelButton.setSizePolicy(sizePolicy)
        self.cancelButton.setObjectName("cancelButton")
        self.ebLayout.addWidget(self.cancelButton, 0, 4, 1, 1)
        self.finishedButton = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.finishedButton.sizePolicy().hasHeightForWidth())
        self.finishedButton.setSizePolicy(sizePolicy)
        self.finishedButton.setObjectName("finishedButton")
        self.ebLayout.addWidget(self.finishedButton, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ebLayout.addItem(spacerItem1, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ebLayout.addItem(spacerItem2, 0, 3, 1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.gridLayout.addWidget(self.hideableBox, 0, 1, 5, 1)
        self.pageFrame = QtWidgets.QFrame(annotator_rhm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageFrame.sizePolicy().hasHeightForWidth())
        self.pageFrame.setSizePolicy(sizePolicy)
        self.pageFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pageFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pageFrame.setObjectName("pageFrame")
        self.pageFrameGrid = QtWidgets.QGridLayout(self.pageFrame)
        self.pageFrameGrid.setContentsMargins(3, 3, 3, 3)
        self.pageFrameGrid.setObjectName("pageFrameGrid")
        self.gridLayout.addWidget(self.pageFrame, 0, 3, 5, 1)
        self.revealBox0 = QtWidgets.QFrame(annotator_rhm)
        self.revealBox0.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.revealBox0.setFrameShadow(QtWidgets.QFrame.Raised)
        self.revealBox0.setObjectName("revealBox0")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.revealBox0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.revealBox1 = QtWidgets.QFrame(self.revealBox0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.revealBox1.sizePolicy().hasHeightForWidth())
        self.revealBox1.setSizePolicy(sizePolicy)
        self.revealBox1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.revealBox1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.revealBox1.setObjectName("revealBox1")
        self.revealLayout = QtWidgets.QGridLayout(self.revealBox1)
        self.revealLayout.setContentsMargins(6, 6, 6, 6)
        self.revealLayout.setSpacing(6)
        self.revealLayout.setObjectName("revealLayout")
        self.deltaButton = QtWidgets.QToolButton(self.revealBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deltaButton.sizePolicy().hasHeightForWidth())
        self.deltaButton.setSizePolicy(sizePolicy)
        self.deltaButton.setMinimumSize(QtCore.QSize(45, 0))
        self.deltaButton.setObjectName("deltaButton")
        self.revealLayout.addWidget(self.deltaButton, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.revealBox1, 0, QtCore.Qt.AlignTop)
        self.revealBox2 = QtWidgets.QFrame(self.revealBox0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.revealBox2.sizePolicy().hasHeightForWidth())
        self.revealBox2.setSizePolicy(sizePolicy)
        self.revealBox2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.revealBox2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.revealBox2.setObjectName("revealBox2")
        self.revealLayout2 = QtWidgets.QVBoxLayout(self.revealBox2)
        self.revealLayout2.setObjectName("revealLayout2")
        self.verticalLayout_2.addWidget(self.revealBox2, 0, QtCore.Qt.AlignBottom)
        self.gridLayout.addWidget(self.revealBox0, 0, 2, 5, 1)

        self.retranslateUi(annotator_rhm)
        QtCore.QMetaObject.connectSlotsByName(annotator_rhm)
        annotator_rhm.setTabOrder(self.finishedButton, self.cancelButton)

    def retranslateUi(self, annotator_rhm):
        _translate = QtCore.QCoreApplication.translate
        annotator_rhm.setWindowTitle(_translate("annotator_rhm", "Annotate paper"))
        self.hideButton.setText(_translate("annotator_rhm", "Compact"))
        self.modeLabel.setText(_translate("annotator_rhm", "mode: move"))
        self.markLabel.setText(_translate("annotator_rhm", "k out of n"))
        self.crossButton.setToolTip(_translate("annotator_rhm", "press e"))
        self.crossButton.setText(_translate("annotator_rhm", "..."))
        self.commentUpButton.setToolTip(_translate("annotator_rhm", "press r"))
        self.commentUpButton.setText(_translate("annotator_rhm", "..."))
        self.tickButton.setToolTip(_translate("annotator_rhm", "press d"))
        self.tickButton.setText(_translate("annotator_rhm", "..."))
        self.commentButton.setToolTip(_translate("annotator_rhm", "press f"))
        self.commentButton.setText(_translate("annotator_rhm", "..."))
        self.boxButton.setToolTip(_translate("annotator_rhm", "press c"))
        self.boxButton.setText(_translate("annotator_rhm", "..."))
        self.commentDownButton.setToolTip(_translate("annotator_rhm", "press v"))
        self.commentDownButton.setText(_translate("annotator_rhm", "..."))
        self.penButton.setToolTip(_translate("annotator_rhm", "press t"))
        self.penButton.setText(_translate("annotator_rhm", "..."))
        self.textButton.setToolTip(_translate("annotator_rhm", "press g"))
        self.textButton.setText(_translate("annotator_rhm", "..."))
        self.lineButton.setToolTip(_translate("annotator_rhm", "press b"))
        self.lineButton.setText(_translate("annotator_rhm", "..."))
        self.deleteButton.setToolTip(_translate("annotator_rhm", "press x"))
        self.deleteButton.setText(_translate("annotator_rhm", "..."))
        self.undoButton.setToolTip(_translate("annotator_rhm", "press s"))
        self.undoButton.setText(_translate("annotator_rhm", "..."))
        self.redoButton.setToolTip(_translate("annotator_rhm", "press w"))
        self.redoButton.setText(_translate("annotator_rhm", "..."))
        self.panButton.setToolTip(_translate("annotator_rhm", "press q"))
        self.panButton.setText(_translate("annotator_rhm", "..."))
        self.zoomButton.setToolTip(_translate("annotator_rhm", "press a"))
        self.zoomButton.setText(_translate("annotator_rhm", "..."))
        self.moveButton.setToolTip(_translate("annotator_rhm", "press z"))
        self.moveButton.setText(_translate("annotator_rhm", "..."))
        self.keyHelpButton.setText(_translate("annotator_rhm", "Key Help"))
        self.finishNoRelaunchButton.setText(_translate("annotator_rhm", "End && \n"
" Return"))
        self.cancelButton.setText(_translate("annotator_rhm", "&Cancel"))
        self.finishedButton.setText(_translate("annotator_rhm", "End && \n"
" Next"))
        self.deltaButton.setText(_translate("annotator_rhm", "..."))
