# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_chooser.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Chooser(object):
    def setupUi(self, Chooser):
        Chooser.setObjectName("Chooser")
        Chooser.resize(411, 474)
        self.verticalLayout = QtWidgets.QVBoxLayout(Chooser)
        self.verticalLayout.setObjectName("verticalLayout")
        self.userGBox = QtWidgets.QGroupBox(Chooser)
        self.userGBox.setEnabled(True)
        self.userGBox.setObjectName("userGBox")
        self.layoutWidget = QtWidgets.QWidget(self.userGBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 371, 72))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.userLE = QtWidgets.QLineEdit(self.layoutWidget)
        self.userLE.setObjectName("userLE")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.userLE)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.passwordLE = QtWidgets.QLineEdit(self.layoutWidget)
        self.passwordLE.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLE.setObjectName("passwordLE")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.passwordLE)
        self.verticalLayout.addWidget(self.userGBox)
        self.serverGBox = QtWidgets.QGroupBox(Chooser)
        self.serverGBox.setEnabled(True)
        self.serverGBox.setObjectName("serverGBox")
        self.layoutWidget1 = QtWidgets.QWidget(self.serverGBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 30, 371, 72))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.serverLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.serverLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.serverLabel.setObjectName("serverLabel")
        self.gridLayout.addWidget(self.serverLabel, 0, 0, 1, 1)
        self.mportLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.mportLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.mportLabel.setObjectName("mportLabel")
        self.gridLayout.addWidget(self.mportLabel, 1, 0, 1, 1)
        self.mportSB = QtWidgets.QSpinBox(self.layoutWidget1)
        self.mportSB.setMaximum(65535)
        self.mportSB.setProperty("value", 41984)
        self.mportSB.setObjectName("mportSB")
        self.gridLayout.addWidget(self.mportSB, 1, 1, 1, 1)
        self.wportLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.wportLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.wportLabel.setObjectName("wportLabel")
        self.gridLayout.addWidget(self.wportLabel, 1, 2, 1, 1)
        self.wportSB = QtWidgets.QSpinBox(self.layoutWidget1)
        self.wportSB.setMaximum(65535)
        self.wportSB.setProperty("value", 41985)
        self.wportSB.setObjectName("wportSB")
        self.gridLayout.addWidget(self.wportSB, 1, 3, 1, 1)
        self.serverLE = QtWidgets.QLineEdit(self.layoutWidget1)
        self.serverLE.setObjectName("serverLE")
        self.gridLayout.addWidget(self.serverLE, 0, 1, 1, 3)
        self.verticalLayout.addWidget(self.serverGBox)
        self.markGBox = QtWidgets.QGroupBox(Chooser)
        self.markGBox.setEnabled(True)
        self.markGBox.setObjectName("markGBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.markGBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.vSB = QtWidgets.QSpinBox(self.markGBox)
        self.vSB.setProperty("value", 1)
        self.vSB.setObjectName("vSB")
        self.gridLayout_2.addWidget(self.vSB, 0, 3, 1, 1)
        self.pgLabel = QtWidgets.QLabel(self.markGBox)
        self.pgLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.pgLabel.setObjectName("pgLabel")
        self.gridLayout_2.addWidget(self.pgLabel, 0, 0, 1, 1)
        self.vlabel = QtWidgets.QLabel(self.markGBox)
        self.vlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.vlabel.setObjectName("vlabel")
        self.gridLayout_2.addWidget(self.vlabel, 0, 2, 1, 1)
        self.pgSB = QtWidgets.QSpinBox(self.markGBox)
        self.pgSB.setProperty("value", 1)
        self.pgSB.setObjectName("pgSB")
        self.gridLayout_2.addWidget(self.pgSB, 0, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout.addWidget(self.markGBox)
        self.taskGBox = QtWidgets.QGroupBox(Chooser)
        self.taskGBox.setObjectName("taskGBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.taskGBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.markButton = QtWidgets.QPushButton(self.taskGBox)
        self.markButton.setObjectName("markButton")
        self.horizontalLayout.addWidget(self.markButton)
        self.identifyButton = QtWidgets.QPushButton(self.taskGBox)
        self.identifyButton.setObjectName("identifyButton")
        self.horizontalLayout.addWidget(self.identifyButton)
        self.totalButton = QtWidgets.QPushButton(self.taskGBox)
        self.totalButton.setObjectName("totalButton")
        self.horizontalLayout.addWidget(self.totalButton)
        self.closeButton = QtWidgets.QPushButton(self.taskGBox)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        self.verticalLayout.addWidget(self.taskGBox)

        self.retranslateUi(Chooser)
        QtCore.QMetaObject.connectSlotsByName(Chooser)
        Chooser.setTabOrder(self.userLE, self.passwordLE)
        Chooser.setTabOrder(self.passwordLE, self.serverLE)
        Chooser.setTabOrder(self.serverLE, self.mportSB)
        Chooser.setTabOrder(self.mportSB, self.wportSB)
        Chooser.setTabOrder(self.wportSB, self.pgSB)
        Chooser.setTabOrder(self.pgSB, self.vSB)
        Chooser.setTabOrder(self.vSB, self.markButton)
        Chooser.setTabOrder(self.markButton, self.identifyButton)
        Chooser.setTabOrder(self.identifyButton, self.totalButton)
        Chooser.setTabOrder(self.totalButton, self.closeButton)

    def retranslateUi(self, Chooser):
        _translate = QtCore.QCoreApplication.translate
        Chooser.setWindowTitle(_translate("Chooser", "Choose your task"))
        self.userGBox.setTitle(_translate("Chooser", "User Information"))
        self.label.setText(_translate("Chooser", "Username"))
        self.label_2.setText(_translate("Chooser", "Password"))
        self.serverGBox.setTitle(_translate("Chooser", "Server Information"))
        self.serverLabel.setText(_translate("Chooser", "Server name"))
        self.mportLabel.setText(_translate("Chooser", "Message port"))
        self.wportLabel.setText(_translate("Chooser", "Webdav port"))
        self.serverLE.setText(_translate("Chooser", "127.0.0.1"))
        self.markGBox.setTitle(_translate("Chooser", "Marking information"))
        self.pgLabel.setText(_translate("Chooser", "Page group"))
        self.vlabel.setText(_translate("Chooser", "Version"))
        self.taskGBox.setTitle(_translate("Chooser", "Choose task"))
        self.markButton.setText(_translate("Chooser", "&Mark"))
        self.identifyButton.setText(_translate("Chooser", "&Identify"))
        self.totalButton.setText(_translate("Chooser", "&Total"))
        self.closeButton.setText(_translate("Chooser", "&Close"))

