# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_marker.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MarkerWindow(object):
    def setupUi(self, MarkerWindow):
        MarkerWindow.setObjectName("MarkerWindow")
        MarkerWindow.resize(1024, 722)
        self.gridLayout_3 = QtWidgets.QGridLayout(MarkerWindow)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.closeButton = QtWidgets.QPushButton(MarkerWindow)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        self.gridLayout_3.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.widget = QtWidgets.QWidget(MarkerWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.userBox = QtWidgets.QGroupBox(self.widget)
        self.userBox.setObjectName("userBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.userBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.userLabel = QtWidgets.QLabel(self.userBox)
        self.userLabel.setObjectName("userLabel")
        self.verticalLayout.addWidget(self.userLabel)
        self.verticalLayout_2.addWidget(self.userBox)
        self.markerBox = QtWidgets.QGroupBox(self.widget)
        self.markerBox.setObjectName("markerBox")
        self.formLayout = QtWidgets.QFormLayout(self.markerBox)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.markerBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.pgLabel = QtWidgets.QLabel(self.markerBox)
        self.pgLabel.setObjectName("pgLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pgLabel)
        self.label_3 = QtWidgets.QLabel(self.markerBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.vLabel = QtWidgets.QLabel(self.markerBox)
        self.vLabel.setObjectName("vLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.vLabel)
        self.label_5 = QtWidgets.QLabel(self.markerBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.scoreLabel = QtWidgets.QLabel(self.markerBox)
        self.scoreLabel.setObjectName("scoreLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.scoreLabel)
        self.verticalLayout_2.addWidget(self.markerBox)
        self.tableBox = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tableBox.sizePolicy().hasHeightForWidth())
        self.tableBox.setSizePolicy(sizePolicy)
        self.tableBox.setObjectName("tableBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tableBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableView = SimpleTableView(self.tableBox)
        self.tableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setObjectName("tableView")
        self.gridLayout_2.addWidget(self.tableView, 0, 0, 1, 3)
        self.nextButton = QtWidgets.QPushButton(self.tableBox)
        self.nextButton.setObjectName("nextButton")
        self.gridLayout_2.addWidget(self.nextButton, 1, 2, 1, 1)
        self.prevButton = QtWidgets.QPushButton(self.tableBox)
        self.prevButton.setObjectName("prevButton")
        self.gridLayout_2.addWidget(self.prevButton, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.tableBox)
        self.buttonFrame = QtWidgets.QFrame(self.widget)
        self.buttonFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttonFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttonFrame.setObjectName("buttonFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.buttonFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.getNextButton = QtWidgets.QPushButton(self.buttonFrame)
        self.getNextButton.setObjectName("getNextButton")
        self.gridLayout.addWidget(self.getNextButton, 0, 0, 1, 1)
        self.annButton = QtWidgets.QPushButton(self.buttonFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.annButton.sizePolicy().hasHeightForWidth())
        self.annButton.setSizePolicy(sizePolicy)
        self.annButton.setObjectName("annButton")
        self.gridLayout.addWidget(self.annButton, 2, 0, 1, 2)
        self.revertButton = QtWidgets.QPushButton(self.buttonFrame)
        self.revertButton.setObjectName("revertButton")
        self.gridLayout.addWidget(self.revertButton, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.buttonFrame)
        self.styleChoiceBox = QtWidgets.QGroupBox(self.widget)
        self.styleChoiceBox.setObjectName("styleChoiceBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.styleChoiceBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.markDownRB = QtWidgets.QRadioButton(self.styleChoiceBox)
        self.markDownRB.setChecked(False)
        self.markDownRB.setObjectName("markDownRB")
        self.markStyleGroup = QtWidgets.QButtonGroup(MarkerWindow)
        self.markStyleGroup.setObjectName("markStyleGroup")
        self.markStyleGroup.addButton(self.markDownRB)
        self.gridLayout_5.addWidget(self.markDownRB, 1, 1, 1, 1)
        self.markTotalRB = QtWidgets.QRadioButton(self.styleChoiceBox)
        self.markTotalRB.setObjectName("markTotalRB")
        self.markStyleGroup.addButton(self.markTotalRB)
        self.gridLayout_5.addWidget(self.markTotalRB, 0, 1, 1, 1)
        self.markLaterRB = QtWidgets.QRadioButton(self.styleChoiceBox)
        self.markLaterRB.setChecked(False)
        self.markLaterRB.setObjectName("markLaterRB")
        self.markStyleGroup.addButton(self.markLaterRB)
        self.gridLayout_5.addWidget(self.markLaterRB, 0, 0, 1, 1)
        self.markUpRB = QtWidgets.QRadioButton(self.styleChoiceBox)
        self.markUpRB.setChecked(True)
        self.markUpRB.setObjectName("markUpRB")
        self.markStyleGroup.addButton(self.markUpRB)
        self.gridLayout_5.addWidget(self.markUpRB, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.styleChoiceBox)
        self.gridLayout_3.addWidget(self.widget, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(MarkerWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.paperBox = QtWidgets.QGroupBox(self.widget_2)
        self.paperBox.setObjectName("paperBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.paperBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_4.addWidget(self.paperBox, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget_2, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.flipButton = QtWidgets.QPushButton(MarkerWindow)
        self.flipButton.setObjectName("flipButton")
        self.horizontalLayout_2.addWidget(self.flipButton)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)

        self.retranslateUi(MarkerWindow)
        QtCore.QMetaObject.connectSlotsByName(MarkerWindow)
        MarkerWindow.setTabOrder(self.getNextButton, self.annButton)
        MarkerWindow.setTabOrder(self.annButton, self.revertButton)
        MarkerWindow.setTabOrder(self.revertButton, self.tableView)
        MarkerWindow.setTabOrder(self.tableView, self.prevButton)
        MarkerWindow.setTabOrder(self.prevButton, self.nextButton)
        MarkerWindow.setTabOrder(self.nextButton, self.flipButton)
        MarkerWindow.setTabOrder(self.flipButton, self.closeButton)

    def retranslateUi(self, MarkerWindow):
        _translate = QtCore.QCoreApplication.translate
        MarkerWindow.setWindowTitle(_translate("MarkerWindow", "Mark papers"))
        self.closeButton.setText(_translate("MarkerWindow", "&Close"))
        self.userBox.setTitle(_translate("MarkerWindow", "User"))
        self.userLabel.setText(_translate("MarkerWindow", "Username"))
        self.markerBox.setTitle(_translate("MarkerWindow", "Marking information"))
        self.label_2.setText(_translate("MarkerWindow", "Pagegroup "))
        self.pgLabel.setText(_translate("MarkerWindow", "NUMBER"))
        self.label_3.setText(_translate("MarkerWindow", "Version"))
        self.vLabel.setText(_translate("MarkerWindow", "NUMBER"))
        self.label_5.setText(_translate("MarkerWindow", "Max score"))
        self.scoreLabel.setText(_translate("MarkerWindow", "NUMBER"))
        self.tableBox.setTitle(_translate("MarkerWindow", "Paper list"))
        self.nextButton.setText(_translate("MarkerWindow", "Next"))
        self.prevButton.setText(_translate("MarkerWindow", "Previous"))
        self.getNextButton.setText(_translate("MarkerWindow", "&Get next"))
        self.annButton.setText(_translate("MarkerWindow", "&Annotate && mark"))
        self.revertButton.setText(_translate("MarkerWindow", "&Revert"))
        self.styleChoiceBox.setTitle(_translate("MarkerWindow", "Marking style"))
        self.markDownRB.setText(_translate("MarkerWindow", "&Mark down"))
        self.markTotalRB.setText(_translate("MarkerWindow", "Mar&k total"))
        self.markLaterRB.setText(_translate("MarkerWindow", "Choose later"))
        self.markUpRB.setText(_translate("MarkerWindow", "Mark &up"))
        self.paperBox.setTitle(_translate("MarkerWindow", "Current paper"))
        self.flipButton.setText(_translate("MarkerWindow", "Flip pages"))

from mlp_useful import SimpleTableView
