# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../qtCreatorFiles/ui_manager.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Manager(object):
    def setupUi(self, Manager):
        Manager.setObjectName("Manager")
        Manager.resize(1024, 660)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(Manager)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tabWidget = QtWidgets.QTabWidget(Manager)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.loginTab = QtWidgets.QWidget()
        self.loginTab.setObjectName("loginTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.loginTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.userGBox = QtWidgets.QGroupBox(self.loginTab)
        self.userGBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.userGBox.sizePolicy().hasHeightForWidth())
        self.userGBox.setSizePolicy(sizePolicy)
        self.userGBox.setObjectName("userGBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.userGBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.userGBox)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.userLE = QtWidgets.QLineEdit(self.userGBox)
        self.userLE.setReadOnly(True)
        self.userLE.setPlaceholderText("")
        self.userLE.setObjectName("userLE")
        self.gridLayout_3.addWidget(self.userLE, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.userGBox)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.passwordLE = QtWidgets.QLineEdit(self.userGBox)
        self.passwordLE.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLE.setObjectName("passwordLE")
        self.gridLayout_3.addWidget(self.passwordLE, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.userGBox)
        self.serverGBox = QtWidgets.QGroupBox(self.loginTab)
        self.serverGBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.serverGBox.sizePolicy().hasHeightForWidth())
        self.serverGBox.setSizePolicy(sizePolicy)
        self.serverGBox.setObjectName("serverGBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.serverGBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.serverLabel = QtWidgets.QLabel(self.serverGBox)
        self.serverLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.serverLabel.setObjectName("serverLabel")
        self.gridLayout_2.addWidget(self.serverLabel, 0, 0, 1, 1)
        self.serverLE = QtWidgets.QLineEdit(self.serverGBox)
        self.serverLE.setObjectName("serverLE")
        self.gridLayout_2.addWidget(self.serverLE, 0, 1, 1, 2)
        self.mportSB = QtWidgets.QSpinBox(self.serverGBox)
        self.mportSB.setMaximum(65535)
        self.mportSB.setProperty("value", 41984)
        self.mportSB.setObjectName("mportSB")
        self.gridLayout_2.addWidget(self.mportSB, 1, 1, 1, 1)
        self.mportLabel = QtWidgets.QLabel(self.serverGBox)
        self.mportLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mportLabel.setObjectName("mportLabel")
        self.gridLayout_2.addWidget(self.mportLabel, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.serverGBox)
        self.fontBox = QtWidgets.QGroupBox(self.loginTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fontBox.sizePolicy().hasHeightForWidth())
        self.fontBox.setSizePolicy(sizePolicy)
        self.fontBox.setObjectName("fontBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.fontBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.fontSB = QtWidgets.QSpinBox(self.fontBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fontSB.sizePolicy().hasHeightForWidth())
        self.fontSB.setSizePolicy(sizePolicy)
        self.fontSB.setMinimum(2)
        self.fontSB.setMaximum(24)
        self.fontSB.setProperty("value", 10)
        self.fontSB.setObjectName("fontSB")
        self.gridLayout_4.addWidget(self.fontSB, 0, 1, 1, 1)
        self.fontLabel = QtWidgets.QLabel(self.fontBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fontLabel.sizePolicy().hasHeightForWidth())
        self.fontLabel.setSizePolicy(sizePolicy)
        self.fontLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.fontLabel.setObjectName("fontLabel")
        self.gridLayout_4.addWidget(self.fontLabel, 0, 0, 1, 1)
        self.fontButton = QtWidgets.QPushButton(self.fontBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fontButton.sizePolicy().hasHeightForWidth())
        self.fontButton.setSizePolicy(sizePolicy)
        self.fontButton.setObjectName("fontButton")
        self.gridLayout_4.addWidget(self.fontButton, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.fontBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loginButton = QtWidgets.QPushButton(self.loginTab)
        self.loginButton.setObjectName("loginButton")
        self.horizontalLayout.addWidget(self.loginButton)
        spacerItem = QtWidgets.QSpacerItem(703, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.loginTab, "")
        self.scanningAllTab = QtWidgets.QWidget()
        self.scanningAllTab.setEnabled(True)
        self.scanningAllTab.setObjectName("scanningAllTab")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.scanningAllTab)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.scanTabW = QtWidgets.QTabWidget(self.scanningAllTab)
        self.scanTabW.setEnabled(True)
        self.scanTabW.setTabPosition(QtWidgets.QTabWidget.North)
        self.scanTabW.setObjectName("scanTabW")
        self.scanTab = QtWidgets.QWidget()
        self.scanTab.setEnabled(True)
        self.scanTab.setObjectName("scanTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scanTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.scanTab)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scanTW = QtWidgets.QTreeWidget(self.groupBox)
        self.scanTW.setAlternatingRowColors(True)
        self.scanTW.setColumnCount(2)
        self.scanTW.setObjectName("scanTW")
        self.scanTW.headerItem().setText(0, "1")
        self.scanTW.headerItem().setText(1, "2")
        self.verticalLayout_3.addWidget(self.scanTW)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.refreshSButton = QtWidgets.QPushButton(self.groupBox)
        self.refreshSButton.setObjectName("refreshSButton")
        self.horizontalLayout_2.addWidget(self.refreshSButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.removePageB = QtWidgets.QPushButton(self.groupBox)
        self.removePageB.setObjectName("removePageB")
        self.horizontalLayout_2.addWidget(self.removePageB)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scanTab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.incompTW = QtWidgets.QTreeWidget(self.groupBox_3)
        self.incompTW.setAlternatingRowColors(True)
        self.incompTW.setColumnCount(2)
        self.incompTW.setObjectName("incompTW")
        self.incompTW.headerItem().setText(0, "1")
        self.incompTW.headerItem().setText(1, "2")
        self.verticalLayout_4.addWidget(self.incompTW)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.refreshIButton = QtWidgets.QPushButton(self.groupBox_3)
        self.refreshIButton.setObjectName("refreshIButton")
        self.horizontalLayout_3.addWidget(self.refreshIButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.subsPageB = QtWidgets.QPushButton(self.groupBox_3)
        self.subsPageB.setObjectName("subsPageB")
        self.horizontalLayout_3.addWidget(self.subsPageB)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.scanTabW.addTab(self.scanTab, "")
        self.unknownTab = QtWidgets.QWidget()
        self.unknownTab.setEnabled(True)
        self.unknownTab.setObjectName("unknownTab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.unknownTab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.unknownTV = QtWidgets.QTableView(self.unknownTab)
        self.unknownTV.setObjectName("unknownTV")
        self.verticalLayout_6.addWidget(self.unknownTV)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.refreshUButton = QtWidgets.QPushButton(self.unknownTab)
        self.refreshUButton.setObjectName("refreshUButton")
        self.horizontalLayout_6.addWidget(self.refreshUButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.actionUButton = QtWidgets.QPushButton(self.unknownTab)
        self.actionUButton.setObjectName("actionUButton")
        self.horizontalLayout_6.addWidget(self.actionUButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.scanTabW.addTab(self.unknownTab, "")
        self.collideTab = QtWidgets.QWidget()
        self.collideTab.setEnabled(True)
        self.collideTab.setObjectName("collideTab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.collideTab)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.collideTV = QtWidgets.QTableView(self.collideTab)
        self.collideTV.setObjectName("collideTV")
        self.verticalLayout_8.addWidget(self.collideTV)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.refreshCButton = QtWidgets.QPushButton(self.collideTab)
        self.refreshCButton.setObjectName("refreshCButton")
        self.horizontalLayout_7.addWidget(self.refreshCButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.actionCButton = QtWidgets.QPushButton(self.collideTab)
        self.actionCButton.setObjectName("actionCButton")
        self.horizontalLayout_7.addWidget(self.actionCButton)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.scanTabW.addTab(self.collideTab, "")
        self.discardTab = QtWidgets.QWidget()
        self.discardTab.setEnabled(True)
        self.discardTab.setObjectName("discardTab")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.discardTab)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.discardTV = QtWidgets.QTableView(self.discardTab)
        self.discardTV.setObjectName("discardTV")
        self.verticalLayout_9.addWidget(self.discardTV)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.refreshDButton = QtWidgets.QPushButton(self.discardTab)
        self.refreshDButton.setObjectName("refreshDButton")
        self.horizontalLayout_8.addWidget(self.refreshDButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.actionDButton = QtWidgets.QPushButton(self.discardTab)
        self.actionDButton.setObjectName("actionDButton")
        self.horizontalLayout_8.addWidget(self.actionDButton)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        self.scanTabW.addTab(self.discardTab, "")
        self.horizontalLayout_13.addWidget(self.scanTabW)
        self.tabWidget.addTab(self.scanningAllTab, "")
        self.progressAllTab = QtWidgets.QWidget()
        self.progressAllTab.setEnabled(True)
        self.progressAllTab.setObjectName("progressAllTab")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.progressAllTab)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.progressTabW = QtWidgets.QTabWidget(self.progressAllTab)
        self.progressTabW.setEnabled(True)
        self.progressTabW.setObjectName("progressTabW")
        self.overallTab = QtWidgets.QWidget()
        self.overallTab.setEnabled(True)
        self.overallTab.setObjectName("overallTab")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.overallTab)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.overallTW = QtWidgets.QTableWidget(self.overallTab)
        self.overallTW.setAlternatingRowColors(True)
        self.overallTW.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.overallTW.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.overallTW.setColumnCount(4)
        self.overallTW.setObjectName("overallTW")
        self.overallTW.setRowCount(0)
        self.overallTW.horizontalHeader().setStretchLastSection(True)
        self.overallTW.verticalHeader().setVisible(False)
        self.verticalLayout_14.addWidget(self.overallTW)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.refreshOButton = QtWidgets.QPushButton(self.overallTab)
        self.refreshOButton.setObjectName("refreshOButton")
        self.horizontalLayout_11.addWidget(self.refreshOButton)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem6)
        self.verticalLayout_14.addLayout(self.horizontalLayout_11)
        self.progressTabW.addTab(self.overallTab, "")
        self.progressTab = QtWidgets.QWidget()
        self.progressTab.setEnabled(True)
        self.progressTab.setObjectName("progressTab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.progressTab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea = QtWidgets.QScrollArea(self.progressTab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.markBucket = QtWidgets.QWidget()
        self.markBucket.setGeometry(QtCore.QRect(0, 0, 64, 16))
        self.markBucket.setObjectName("markBucket")
        self.scrollArea.setWidget(self.markBucket)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.refreshPButton = QtWidgets.QPushButton(self.progressTab)
        self.refreshPButton.setObjectName("refreshPButton")
        self.horizontalLayout_4.addWidget(self.refreshPButton)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.progressTabW.addTab(self.progressTab, "")
        self.idTab = QtWidgets.QWidget()
        self.idTab.setEnabled(True)
        self.idTab.setObjectName("idTab")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.idTab)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.groupBox_2 = QtWidgets.QGroupBox(self.idTab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 2)
        self.papersLE = QtWidgets.QLineEdit(self.groupBox_2)
        self.papersLE.setReadOnly(True)
        self.papersLE.setObjectName("papersLE")
        self.gridLayout.addWidget(self.papersLE, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 2)
        self.totPB = QtWidgets.QProgressBar(self.groupBox_2)
        self.totPB.setProperty("value", 0)
        self.totPB.setObjectName("totPB")
        self.gridLayout.addWidget(self.totPB, 2, 2, 1, 1)
        self.idPB = QtWidgets.QProgressBar(self.groupBox_2)
        self.idPB.setProperty("value", 0)
        self.idPB.setObjectName("idPB")
        self.gridLayout.addWidget(self.idPB, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 2)
        self.verticalLayout_11.addLayout(self.gridLayout)
        self.refreshIDButon = QtWidgets.QPushButton(self.groupBox_2)
        self.refreshIDButon.setObjectName("refreshIDButon")
        self.verticalLayout_11.addWidget(self.refreshIDButon)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem8)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.selectRectButton = QtWidgets.QPushButton(self.groupBox_4)
        self.selectRectButton.setObjectName("selectRectButton")
        self.verticalLayout_12.addWidget(self.selectRectButton)
        self.predictButton = QtWidgets.QPushButton(self.groupBox_4)
        self.predictButton.setEnabled(False)
        self.predictButton.setObjectName("predictButton")
        self.verticalLayout_12.addWidget(self.predictButton)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem9)
        self.delPredButton = QtWidgets.QPushButton(self.groupBox_4)
        self.delPredButton.setObjectName("delPredButton")
        self.verticalLayout_12.addWidget(self.delPredButton)
        self.verticalLayout_11.addWidget(self.groupBox_4)
        self.horizontalLayout_9.addLayout(self.verticalLayout_11)
        self.predGB = QtWidgets.QGroupBox(self.groupBox_2)
        self.predGB.setObjectName("predGB")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.predGB)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.predictionTW = QtWidgets.QTableWidget(self.predGB)
        self.predictionTW.setAlternatingRowColors(True)
        self.predictionTW.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.predictionTW.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectColumns)
        self.predictionTW.setColumnCount(3)
        self.predictionTW.setObjectName("predictionTW")
        self.predictionTW.setRowCount(0)
        self.predictionTW.horizontalHeader().setStretchLastSection(True)
        self.predictionTW.verticalHeader().setVisible(False)
        self.verticalLayout_13.addWidget(self.predictionTW)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem10)
        self.predListRefreshB = QtWidgets.QPushButton(self.predGB)
        self.predListRefreshB.setObjectName("predListRefreshB")
        self.horizontalLayout_10.addWidget(self.predListRefreshB)
        self.verticalLayout_13.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9.addWidget(self.predGB)
        self.verticalLayout_10.addWidget(self.groupBox_2)
        self.progressTabW.addTab(self.idTab, "")
        self.horizontalLayout_14.addWidget(self.progressTabW)
        self.tabWidget.addTab(self.progressAllTab, "")
        self.reviewAllTab = QtWidgets.QWidget()
        self.reviewAllTab.setEnabled(True)
        self.reviewAllTab.setObjectName("reviewAllTab")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.reviewAllTab)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.reviewAllTab)
        self.tabWidget_4.setEnabled(True)
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.reviewMTab = QtWidgets.QWidget()
        self.reviewMTab.setEnabled(True)
        self.reviewMTab.setObjectName("reviewMTab")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.reviewMTab)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_6 = QtWidgets.QLabel(self.reviewMTab)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_15.addWidget(self.label_6)
        self.questionCB = QtWidgets.QComboBox(self.reviewMTab)
        self.questionCB.setObjectName("questionCB")
        self.verticalLayout_15.addWidget(self.questionCB)
        self.horizontalLayout_12.addLayout(self.verticalLayout_15)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_7 = QtWidgets.QLabel(self.reviewMTab)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_16.addWidget(self.label_7)
        self.versionCB = QtWidgets.QComboBox(self.reviewMTab)
        self.versionCB.setObjectName("versionCB")
        self.verticalLayout_16.addWidget(self.versionCB)
        self.horizontalLayout_12.addLayout(self.verticalLayout_16)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_8 = QtWidgets.QLabel(self.reviewMTab)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_17.addWidget(self.label_8)
        self.userCB = QtWidgets.QComboBox(self.reviewMTab)
        self.userCB.setObjectName("userCB")
        self.verticalLayout_17.addWidget(self.userCB)
        self.horizontalLayout_12.addLayout(self.verticalLayout_17)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem11)
        self.filterB = QtWidgets.QPushButton(self.reviewMTab)
        self.filterB.setObjectName("filterB")
        self.horizontalLayout_12.addWidget(self.filterB)
        self.verticalLayout_19.addLayout(self.horizontalLayout_12)
        self.reviewTW = QtWidgets.QTableWidget(self.reviewMTab)
        self.reviewTW.setAlternatingRowColors(True)
        self.reviewTW.setColumnCount(7)
        self.reviewTW.setObjectName("reviewTW")
        self.reviewTW.setRowCount(0)
        self.reviewTW.horizontalHeader().setStretchLastSection(True)
        self.reviewTW.verticalHeader().setVisible(False)
        self.reviewTW.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_19.addWidget(self.reviewTW)
        self.tabWidget_4.addTab(self.reviewMTab, "")
        self.ReviewITab = QtWidgets.QWidget()
        self.ReviewITab.setObjectName("ReviewITab")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.ReviewITab)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.reviewIDTW = QtWidgets.QTableWidget(self.ReviewITab)
        self.reviewIDTW.setObjectName("reviewIDTW")
        self.reviewIDTW.setColumnCount(0)
        self.reviewIDTW.setRowCount(0)
        self.reviewIDTW.horizontalHeader().setStretchLastSection(True)
        self.reviewIDTW.verticalHeader().setVisible(False)
        self.verticalLayout_18.addWidget(self.reviewIDTW)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.refreshIDB = QtWidgets.QPushButton(self.ReviewITab)
        self.refreshIDB.setObjectName("refreshIDB")
        self.horizontalLayout_16.addWidget(self.refreshIDB)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem12)
        self.verticalLayout_18.addLayout(self.horizontalLayout_16)
        self.tabWidget_4.addTab(self.ReviewITab, "")
        self.reviewTTab = QtWidgets.QWidget()
        self.reviewTTab.setEnabled(True)
        self.reviewTTab.setObjectName("reviewTTab")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.reviewTTab)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.reviewTOTTW = QtWidgets.QTableWidget(self.reviewTTab)
        self.reviewTOTTW.setObjectName("reviewTOTTW")
        self.reviewTOTTW.setColumnCount(0)
        self.reviewTOTTW.setRowCount(0)
        self.reviewTOTTW.horizontalHeader().setCascadingSectionResizes(True)
        self.verticalLayout_20.addWidget(self.reviewTOTTW)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.refreshTOTB = QtWidgets.QPushButton(self.reviewTTab)
        self.refreshTOTB.setObjectName("refreshTOTB")
        self.horizontalLayout_17.addWidget(self.refreshTOTB)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem13)
        self.verticalLayout_20.addLayout(self.horizontalLayout_17)
        self.tabWidget_4.addTab(self.reviewTTab, "")
        self.horizontalLayout_15.addWidget(self.tabWidget_4)
        self.tabWidget.addTab(self.reviewAllTab, "")
        self.verticalLayout_7.addWidget(self.tabWidget)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem14)
        self.closeButton = QtWidgets.QPushButton(Manager)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_5.addWidget(self.closeButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)

        self.retranslateUi(Manager)
        self.tabWidget.setCurrentIndex(0)
        self.scanTabW.setCurrentIndex(0)
        self.progressTabW.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Manager)
        Manager.setTabOrder(self.passwordLE, self.serverLE)
        Manager.setTabOrder(self.serverLE, self.mportSB)
        Manager.setTabOrder(self.mportSB, self.loginButton)
        Manager.setTabOrder(self.loginButton, self.fontSB)
        Manager.setTabOrder(self.fontSB, self.fontButton)
        Manager.setTabOrder(self.fontButton, self.tabWidget)
        Manager.setTabOrder(self.tabWidget, self.userLE)
        Manager.setTabOrder(self.userLE, self.scanTW)
        Manager.setTabOrder(self.scanTW, self.refreshSButton)
        Manager.setTabOrder(self.refreshSButton, self.removePageB)
        Manager.setTabOrder(self.removePageB, self.incompTW)
        Manager.setTabOrder(self.incompTW, self.refreshIButton)
        Manager.setTabOrder(self.refreshIButton, self.subsPageB)
        Manager.setTabOrder(self.subsPageB, self.overallTW)
        Manager.setTabOrder(self.overallTW, self.refreshOButton)
        Manager.setTabOrder(self.refreshOButton, self.papersLE)
        Manager.setTabOrder(self.papersLE, self.refreshIDButon)
        Manager.setTabOrder(self.refreshIDButon, self.selectRectButton)
        Manager.setTabOrder(self.selectRectButton, self.predictButton)
        Manager.setTabOrder(self.predictButton, self.delPredButton)
        Manager.setTabOrder(self.delPredButton, self.predictionTW)
        Manager.setTabOrder(self.predictionTW, self.predListRefreshB)
        Manager.setTabOrder(self.predListRefreshB, self.scrollArea)
        Manager.setTabOrder(self.scrollArea, self.refreshPButton)
        Manager.setTabOrder(self.refreshPButton, self.unknownTV)
        Manager.setTabOrder(self.unknownTV, self.refreshUButton)
        Manager.setTabOrder(self.refreshUButton, self.actionUButton)
        Manager.setTabOrder(self.actionUButton, self.collideTV)
        Manager.setTabOrder(self.collideTV, self.refreshCButton)
        Manager.setTabOrder(self.refreshCButton, self.actionCButton)
        Manager.setTabOrder(self.actionCButton, self.discardTV)
        Manager.setTabOrder(self.discardTV, self.refreshDButton)
        Manager.setTabOrder(self.refreshDButton, self.actionDButton)
        Manager.setTabOrder(self.actionDButton, self.closeButton)

    def retranslateUi(self, Manager):
        _translate = QtCore.QCoreApplication.translate
        Manager.setWindowTitle(_translate("Manager", "Overview and Management"))
        self.userGBox.setTitle(_translate("Manager", "User Information"))
        self.label.setText(_translate("Manager", "Username"))
        self.userLE.setText(_translate("Manager", "manager"))
        self.label_2.setText(_translate("Manager", "Password"))
        self.serverGBox.setTitle(_translate("Manager", "Server Information"))
        self.serverLabel.setText(_translate("Manager", "Server name:"))
        self.serverLE.setText(_translate("Manager", "127.0.0.1"))
        self.mportLabel.setText(_translate("Manager", "Port:"))
        self.fontBox.setTitle(_translate("Manager", "Font size"))
        self.fontLabel.setText(_translate("Manager", "Font size"))
        self.fontButton.setText(_translate("Manager", "Set font"))
        self.loginButton.setText(_translate("Manager", "&Login"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.loginTab), _translate("Manager", "Login"))
        self.groupBox.setTitle(_translate("Manager", "Completely scanned papers"))
        self.refreshSButton.setText(_translate("Manager", "Refresh"))
        self.removePageB.setText(_translate("Manager", "Remove page from server"))
        self.groupBox_3.setTitle(_translate("Manager", "Incomplete papers"))
        self.refreshIButton.setText(_translate("Manager", "Refresh"))
        self.subsPageB.setText(_translate("Manager", "Substitute missing page with blank"))
        self.scanTabW.setTabText(self.scanTabW.indexOf(self.scanTab), _translate("Manager", "&Scan Status"))
        self.refreshUButton.setText(_translate("Manager", "Refresh"))
        self.actionUButton.setText(_translate("Manager", "Perform actions"))
        self.scanTabW.setTabText(self.scanTabW.indexOf(self.unknownTab), _translate("Manager", "&Unknown Pages"))
        self.refreshCButton.setText(_translate("Manager", "&Refresh"))
        self.actionCButton.setText(_translate("Manager", "Perfrom actions"))
        self.scanTabW.setTabText(self.scanTabW.indexOf(self.collideTab), _translate("Manager", "&Colliding Pages"))
        self.refreshDButton.setText(_translate("Manager", "Refresh"))
        self.actionDButton.setText(_translate("Manager", "Perform actions"))
        self.scanTabW.setTabText(self.scanTabW.indexOf(self.discardTab), _translate("Manager", "&Discarded Pages"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.scanningAllTab), _translate("Manager", "&Scanning"))
        self.refreshOButton.setText(_translate("Manager", "Refresh"))
        self.progressTabW.setTabText(self.progressTabW.indexOf(self.overallTab), _translate("Manager", "&Overall Progress"))
        self.refreshPButton.setText(_translate("Manager", "Refresh"))
        self.progressTabW.setTabText(self.progressTabW.indexOf(self.progressTab), _translate("Manager", "&Marking Progress"))
        self.groupBox_2.setTitle(_translate("Manager", "ID and Totalling progress, and ID predictions"))
        self.label_3.setText(_translate("Manager", "Number of papers:"))
        self.label_5.setText(_translate("Manager", "Totalling progress"))
        self.label_4.setText(_translate("Manager", "ID progress"))
        self.refreshIDButon.setText(_translate("Manager", "Refresh"))
        self.groupBox_4.setTitle(_translate("Manager", "Read student numbers from ID pages"))
        self.selectRectButton.setText(_translate("Manager", "Select ID rectangle"))
        self.predictButton.setText(_translate("Manager", "Run predictions"))
        self.delPredButton.setText(_translate("Manager", "Delete predictions"))
        self.predGB.setTitle(_translate("Manager", "ID prediction list"))
        self.predictionTW.setSortingEnabled(True)
        self.predListRefreshB.setText(_translate("Manager", "Refresh List"))
        self.progressTabW.setTabText(self.progressTabW.indexOf(self.idTab), _translate("Manager", "&ID && Totalling Progress"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.progressAllTab), _translate("Manager", "&Progress"))
        self.label_6.setText(_translate("Manager", "Question"))
        self.label_7.setText(_translate("Manager", "Version"))
        self.label_8.setText(_translate("Manager", "Username"))
        self.filterB.setText(_translate("Manager", "&Filter"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.reviewMTab), _translate("Manager", "Review &Marking"))
        self.reviewIDTW.setSortingEnabled(True)
        self.refreshIDB.setText(_translate("Manager", "Refresh"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.ReviewITab), _translate("Manager", "Review &ID"))
        self.refreshTOTB.setText(_translate("Manager", "Refresh"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.reviewTTab), _translate("Manager", "Review &Totalling"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.reviewAllTab), _translate("Manager", "&Review"))
        self.closeButton.setText(_translate("Manager", "&Quit"))
