# Generated by Django 5.2.1 on 2025-07-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Papers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specquestion",
            name="select",
            field=models.JSONField(null=True),
        ),
    ]
