# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2025 Bryan Tanady

# Defines where are the model weights stored

models:
  hme:
    symbolic: "model_cache/hme_symbolic.onnx"
    trocr: "model_cache/hme_trOCR.onnx"
  mcq: "model_cache/mcq_model.onnx"