# Generated by Django 4.0.6 on 2022-08-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreserverconnection',
            name='port_number',
            field=models.IntegerField(default=41984),
        ),
        migrations.AlterField(
            model_name='coreserverconnection',
            name='server_url',
            field=models.TextField(default='localhost'),
        ),
    ]
