# Generated by Django 4.0.6 on 2022-08-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connect', '0002_coreserverconnection_port_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreserverconnection',
            name='api',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='coreserverconnection',
            name='client_version',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='coreserverconnection',
            name='port_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coreserverconnection',
            name='server_url',
            field=models.TextField(default=''),
        ),
    ]
