# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2023 Edith Coates
# Copyright (C) 2024, 2026 Colin B. Macdonald
# Copyright (C) 2024 Aidan Murphy

import json
from typing import Any

from django.db import models
from django.contrib.auth.models import User
from . import MarkingTask


class AnnotationImage(models.Model):
    """A raster representation of an annotated question.

    Attributes:
        image: a jpeg or png file.
        hash: a string of a hash of the file, currently the md5sum.

    Because of the OneToOneField in Annotation, there will also be an
    autogenerated field called ``annotation`` (note lowercase).
    """

    image = models.FileField(upload_to="annotation_images/", null=False)
    hash = models.TextField(null=False, default="")


class Annotation(models.Model):
    """Represents a marker's annotation of a particular paper's question.

    Attributes:
        edition: The edition of the annotation for the specified task.
        score: The score given to the student's work.
        image: The image of the annotated question.
        marking_time: The total cumulative time in seconds spent by all
            markers on this question of this paper.  As a question gets
            remarked or revisited this number will increase.
        marking_delta_time: the time in seconds spent making this
            particular annotation (which could be a revision to a
            previous annotation).  The total ``marking_time`` is thus
            the sum of all the ``marking_delta_time`` over all revisions.
        task: The marking task.
        user: The user who made the annotation.
        time_of_last_update: The time of the last update.
        user_agent: a string describing the client reasponsible for this
            Annotation.  At most 64 chars.  Could be a uuid or a string
            such as "org.plomgrading.PlomClient".
        user_agent_version: the version of the user agent such as "1.3.7"
            or "0.22.3.dev0".
        annotation_data: A blob of data encoded as an ascii-string.
            We generally don't look at this: the client sends something
            and can get it back to reconstruct the scene for further
            editing.  This will generally be a JSON blob, written to
            a string with Python's ``json.dumps`` for example.  It could
            also be a uuencoded binary data or whatever the client sees
            bit.  It should not be excessively large: think SVG not
            large bitmap data.  If a client needs large binary data,
            we could consider a file-based mechanism in the future.
    """

    edition = models.IntegerField(null=True)
    score = models.FloatField(null=True)
    image = models.OneToOneField(AnnotationImage, on_delete=models.CASCADE)
    marking_time = models.FloatField(null=True)
    marking_delta_time = models.FloatField(null=True)
    task = models.ForeignKey(MarkingTask, null=True, on_delete=models.SET_NULL)
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    time_of_last_update = models.DateTimeField(auto_now=True)
    user_agent = models.CharField(null=False, blank=True, max_length=64)
    user_agent_version = models.CharField(null=False, blank=True, max_length=64)
    annotation_data = models.TextField(null=False, blank=True)

    def _get_annotation_data(self) -> dict[str, Any]:
        """Perhaps temporary, but some parts of the code need the actual annotation data.

        Unpack it, assuming its JSON, in contradiction with the docs above.
        """
        return json.loads(self.annotation_data)
